# checking dropout with convolutional input

In [1]:
import torch

In [3]:
a = torch.rand(size=(10,3,9,9))

In [4]:
a[0][0]

tensor([[0.1778, 0.7016, 0.6622, 0.6064, 0.4926, 0.9568, 0.5801, 0.4622, 0.0534],
        [0.1580, 0.4153, 0.0963, 0.4467, 0.3285, 0.7584, 0.9245, 0.8254, 0.2960],
        [0.7138, 0.1868, 0.8126, 0.4354, 0.0418, 0.5345, 0.6155, 0.1883, 0.0128],
        [0.3872, 0.0768, 0.6804, 0.3137, 0.4320, 0.3258, 0.8519, 0.9916, 0.2220],
        [0.8366, 0.2544, 0.6126, 0.6219, 0.0047, 0.3863, 0.7217, 0.1556, 0.8703],
        [0.3117, 0.1642, 0.5693, 0.4424, 0.5885, 0.5475, 0.1451, 0.2196, 0.0374],
        [0.3411, 0.4574, 0.6424, 0.0433, 0.6089, 0.1919, 0.1416, 0.9189, 0.3324],
        [0.1441, 0.4436, 0.4237, 0.8209, 0.5592, 0.5666, 0.5536, 0.4123, 0.1522],
        [0.8201, 0.0117, 0.4775, 0.8544, 0.5196, 0.9659, 0.2612, 0.4599, 0.7818]])

In [13]:
dropout = torch.nn.Dropout(p=0.5, inplace=False)
dropout2d = torch.nn.Dropout2d(p=0.5, inplace=False)

In [7]:
a_new = dropout(a)

In [12]:
a_new[0][0]

tensor([[0.0000, 1.4032, 1.3244, 0.0000, 0.0000, 1.9136, 0.0000, 0.0000, 0.0000],
        [0.3160, 0.8307, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.4276, 0.3736, 1.6253, 0.0000, 0.0837, 0.0000, 1.2310, 0.3766, 0.0257],
        [0.0000, 0.1535, 1.3607, 0.0000, 0.0000, 0.6516, 0.0000, 1.9832, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0093, 0.0000, 1.4434, 0.3112, 1.7405],
        [0.6234, 0.0000, 1.1387, 0.0000, 1.1771, 1.0950, 0.2902, 0.4392, 0.0747],
        [0.6822, 0.9148, 0.0000, 0.0000, 1.2178, 0.3837, 0.2832, 1.8377, 0.6647],
        [0.2882, 0.8872, 0.8473, 1.6417, 0.0000, 0.0000, 0.0000, 0.0000, 0.3045],
        [0.0000, 0.0234, 0.9551, 0.0000, 1.0392, 1.9317, 0.5225, 0.0000, 0.0000]])

In [22]:
a2 = dropout2d(a)

In [23]:
a2[0][2]

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])