# understand how DropBlock works

In [1]:
import torch
from dropblock import DropBlock

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '2'

In [3]:
print('Using GPUs: ', os.environ["CUDA_VISIBLE_DEVICES"])

Using GPUs:  2


In [4]:
db = DropBlock(block_size=3)

In [5]:
db.training

True

In [6]:
a = torch.ones(size=(1,2,7,7), dtype=torch.float32)

In [7]:
db(a, gamma=0.1)

tensor([[[[1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627],
          [1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627],
          [1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627],
          [1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627],
          [1.4627, 1.4627, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [1.4627, 1.4627, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [1.4627, 1.4627, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

         [[1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627],
          [1.4627, 0.0000, 0.0000, 0.0000, 1.4627, 1.4627, 1.4627],
          [1.4627, 0.0000, 0.0000, 0.0000, 1.4627, 1.4627, 1.4627],
          [0.0000, 0.0000, 0.0000, 0.0000, 1.4627, 1.4627, 1.4627],
          [0.0000, 0.0000, 0.0000, 1.4627, 1.4627, 1.4627, 1.4627],
          [0.0000, 0.0000, 0.0000, 1.4627, 1.4627, 1.4627, 1.4627],
          [1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627, 1.4627]]]])

In [8]:
block_size = 3

In [9]:
torch.arange(block_size).view(-1, 1).expand(block_size, block_size).reshape(-1).t()

tensor([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [10]:
torch.arange(block_size).repeat(block_size)

tensor([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [11]:
offsets = torch.stack(
        [
            torch.arange(block_size).view(-1, 1).expand(block_size, block_size).reshape(-1), # - left_padding,
            torch.arange(block_size).repeat(block_size), #- left_padding
        ]).t()

In [12]:
offsets

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])

In [13]:
offsets = offsets.repeat(10, 1)